### PR TITLE
Add setting view

### PR DESCRIPTION
**Pull request by vomchik**
Now user can choses default preset(#6) and es6 support(#13)

### CODE REVIEW

**Comment by foliveira** [comment]
Thanks @vomchik.

But the actual settings view where the user can configure this options, seems to be missing no?

**Comment by vomchik** [comment]
No! I used Atom config system. This view present on package page in editor.

**Comment by vomchik** [comment]
See https://github.com/foliveira/jscs-fixer/pull/14/files#diff-7ee8530b97fcd27f0aaff73275972d4aR66

**Comment by foliveira** [comment]
Hey @vomchik, didn't know about it. It's really cool.

**Comment by foliveira** [comment]
Hey @vomchik, didn't know about it. 

It's really cool.

Once more, thank you!

**Comment by foliveira** [comment]
Also, I'm going to publish this as version 0.4.0 in a few moments.

It also closes #6 and #13 (and I think #14)

**Comment by vomchik** [comment]
ok

**Pull request merged**
